### ISSUE TITLE
Introduce local H@H blacklist

### ISSUE THREAD

**Issue by revonateB0T** [FooIbar/EhViewer#2045]
Following #1915 
We temporally ban timed out H@H for several weeks.

**Comment by yinzhefuyun** [comment]
我劝你别搞这个功能，你可能没有关注过E战站长发的新闻，而且那是之前的问题，现在好像已经取消了，或者说快取消了，就是E站站长随机给中国IP和H@H投毒用来惩罚那写批量下载的人（点开直接开始下载，不是正常看的那种人）
`2024-07-23

- Due to unbalanced traffic caused by missing round-robin allocation on third party clients effectively causing a DDoS condition, IPv6 on thumbnail servers has been disabled until further notice, and random subsets of Chinese IPv4 ranges have been blocked on different thumbnail servers to force them to use different servers.

This will remain until the majority of Chinese traffic use the available round-robin balancing properly.`

**Comment by yinzhefuyun** [comment]
> H@H投毒是中国人自己干的，往里塞篡改的图片。

卧槽，还有人这样搞？？？为了打广告？

**Comment by yinzhefuyun** [comment]
> 如果你不知道，哪来的投毒的用法？ 无论是DNS还是H@H的投毒都是谁在做啊？
> 
> thumbnail servers 那时候是固定的的几个服务器，不是志愿者分发，所以才会过载要限制。这里提到的是H@H，和那个没有关系。 所以你可以撤回那堆无稽之谈了吗？

没必要撤回，错了就是错了放在那里就好了，撤回就像有些论坛有人发帖询问问题，解答后删除正文一样，给别人添乱，你回答不删就好了
